### ISSUE TITLE
DB metrics

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tm-db#105]
should there be an option to expose metrics on the provided databases?

I was thinking it would be nice to expose some sort of metrics of the databases for testing and/or useage by node operators.

**Comment by erikgrinaker** [comment]
We already do, [`DB.Stats()`](https://github.com/tendermint/tm-db/blob/f4a6a3573f4b58771994240b92333813ca293608/types.go#L69).

**Comment by marbar3778** [comment]
whoops missed that, thank you
