### ISSUE TITLE
Follow-up on boltdb integration

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tm-db#17]
Particularly:
 - https://github.com/tendermint/tendermint/pull/3610#pullrequestreview-233751678
 - https://github.com/tendermint/tendermint/pull/3610#discussion_r280995538
 - https://github.com/tendermint/tendermint/pull/3610#discussion_r281201274
 - https://github.com/tendermint/tendermint/pull/3610#discussion_r280132399

Maybe we should mark boltdb support as highly experimental and not throughly tested in the changelog, too. Also mention where bbolt could be useful (e.g. read-heavy applications?).

ref: tendermint/tendermint#3610, tendermint/tendermint#3611

**Comment by erikgrinaker** [comment]
We have marked BoltDB as experimental in the README, described its tradeoffs, fixed a bunch of bugs, and ported it to the common test suite used by all backends.
