### ISSUE TITLE
Switch to original techbot rocksdb wrapper

### ISSUE THREAD

**Issue by melekes** [tendermint/tm-db#18]
See https://github.com/tendermint/tm-db/pull/12#issuecomment-520004912

As of now (Sep 18, 2019) it looks like techbot repo is unmaintained.

**Comment by Stumble** [comment]
The PR, https://github.com/tecbot/gorocksdb/commit/d217d93fd4c523de2da5dbfdf06c3ef496dc2b34, is merged, let's switch to the original repo.

**Comment by marbar3778** [comment]
https://github.com/tendermint/tm-db/pull/24
