### ISSUE TITLE
memdb: Implement btree.Item on `item` directly, in addition to `*item`

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tm-db#186]
Currently we force every btree item to be `*item`, not just `item`. This in turn causes every set to require new heap allocations, which turns out to be a significant overhead. These allocations cause lots of memory to need to be garbage collected, and this ends up often being the bottleneck, not the actual btree searching operations.

In Osmosis, we get that we have ~no item spent in the btree operations, its all spent in allocating the `newPair` onto Heap. Heres a screenshot of a relevant flamegraph output here: 
<img width="1502" alt="Screenshot 2021-09-03 at 12 28 35 PM" src="https://user-images.githubusercontent.com/6440154/132045005-770a203e-d22f-4c0c-b6eb-d9a8ba03cbeb.png">

**Comment by marbar3778** [comment]
Hey, I can help in getting a release out to fix this, if you are willing to make a PR. I can push a branch for you to target as master has diverged too much to be used for this

**Comment by ValarDragon** [comment]
smh stale bot

**Comment by ValarDragon** [comment]
Can we please remove stale bot issue closing =/ Its not even that long of a wait atm

**Comment by marbar3778** [comment]
yea ill fix

**Comment by faddat** [comment]
What's the status of this one?

I guess I want to include it in the notinal tracking issue

@ValarDragon do you think this is needed still?

**Comment by ValarDragon** [comment]
Yeah this is still useful

**Comment by faddat** [comment]
great!

**Comment by faddat** [comment]
So, fair to say this one is more important than #188 ?

that’s good because ah, wow

Pain is a teacher I guess?

**Comment by faddat** [comment]
Seems set :)
