### ISSUE TITLE
libs/db: disallow empty keys

### ISSUE THREAD

**Issue by melekes** [tendermint/tm-db#2]
See https://github.com/tendermint/tendermint/pull/3610#discussion_r280053143

Reasons to do that:
- many KV stores does not support empty keys
- I don't know why would someone want to set en empty key (and not call it `default` or something else)

**Comment by erikgrinaker** [comment]
I'm making some breaking changes to the interface shortly, suggest we do this at the same time since there are a few issues with empty keys (notably BoltDB not supporting it, and cLevelDB panics). Any objections?
