### ISSUE TITLE
Performance review

### ISSUE THREAD

**Issue by faddat** [tendermint/tm-db#211]
# goleveldb
https://youtu.be/Ho6DHkZax2c

# badgerdb
https://youtu.be/tITLgGKDMDc

# rocksdb
https://youtu.be/47PWHwkM0MY

All of notional's relay infrastructure has had to adopt rocksdb (osmosis, terra, gaia, juno) out of necessity.  Given the overwhelming improvement, is there any reason not to work it into default workflows (slowly and in a non-jarring manner)

3xish is pretty good-- as is so far-- 100% compatibly.  

# Reasons not to rocksdb

* not all go makes compiles not super fun:

https://github.com/cosmos/gorocksdb/pull/3

* pebbledb?
https://github.com/cockroachdb/pebble

**Comment by faddat** [comment]
https://github.com/cockroachdb/pebble/blob/e2a8aef27e1b170d78f466fb97fda036a693abab/batch.go#L418

https://github.com/cockroachdb/pebble/issues/1416

**Comment by boz** [comment]
3x on a drop-in-ish replacement is amazing @faddat!

I think that by defining a [prefix extractor](https://github.com/facebook/rocksdb/wiki/Prefix-Seek#defining-a-prefix) that partitions by store key prefixes, we may be able to get a big boost in query performance.

**Comment by marbar3778** [comment]
Hey, it seems there is some increased performance in your video, but it would be good to get benchmarks and profiles to see the increased performance. Also I believe you would see similar performance across all dbs when they grow in size. 

At the end, write performance is not a major issue in the sdk. We are working on changes in IAVL to improve read performance which will improve writes while state executing. This theory was put together through profiling.

**Comment by faddat** [comment]
@marbar3778 could we arrange a call or DM session to discuss relaying?

The issue is reads and I don't know how to properly quantify but this helps a great deal there, too,

**Comment by marbar3778** [comment]
Happy to hop on a call!! this is helping push forward on things.

**Comment by faddat** [comment]
@boz -- @marbar3778 explained to me a bit more how we look for things in iavl, and I totally agree, those prefixes should help with performance a great deal.

**Comment by faddat** [comment]
This is superceded by #248
