### ISSUE TITLE
rocksdb: pedantic error checks that could just be direct returns

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tm-db#263]
If we examine the code in RocksDB, we can see this pedantic pattern that could instead be a direct return
![image](https://user-images.githubusercontent.com/4898263/172494232-1c8466ca-9fc6-4e1a-80fa-7013feb21334.jpeg)

**Comment by faddat** [comment]
* nice commentary
* nice use of ipad
* agree

but the key thing is that we don't use rocksdb v7

**Comment by odeke-em** [comment]
Thanks @faddat for the reply and for fixing this issue. Ahah nice that you noticed it was an iPad
