### ISSUE TITLE
leveldb: detect corruption

### ISSUE THREAD

**Issue by melekes** [tendermint/tm-db#3]
>LevelDB is widely noted for being unreliable and databases it manages are prone to corruption.[14][15][16][17][18][19] Academic studies of past versions of LevelDB[20] have found that, under some file systems, the data stored in those versions of LevelDB might become inconsistent after a system crash or power failure. LevelDB corruption is so commonplace that corruption detection has to be built into applications that use it.

source: https://en.wikipedia.org/wiki/LevelDB

I think we should checksum the data. The alternative suggested here https://github.com/tendermint/tendermint/issues/1835#issuecomment-421062709 is to switch to a different db (offering better guarantees) and speed.

**Comment by erikgrinaker** [comment]
This is really the database's responsibility, and there's a limit to how much we can do about it in the application. If the database can't avoid corruption on its own, we shouldn't be using it.

>I think we should checksum the data.

Per-value or for the entire dataset? The former is rather limited (won't detect addition, removal, or cross-key inconsistencies), while the latter is prohibitively expensive.

**Comment by melekes** [comment]
> Per-value or for the entire dataset?

I meant per-value. But I agree, DB should do it, not us!
