### ISSUE TITLE
libs/db: path traversal

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tm-db#5]
Due to how the `dir` is handled here:
https://github.com/tendermint/tendermint/blob/40d6dc2ee55a34a075e7b7e73c3525c84ae705ea/libs/db/fsdb.go#L22-L25

the following code will create a directory in e.g., `/tmp/mbdb.db/`:
```go
package main

import "github.com/tendermint/tendermint/libs/db"

func main() {
	db := db.NewDB("../../tmp/mydb", "fsdb","/home/tendermint/")
	db.Set([]byte("foo"),[]byte("bar"))
}
```

We can assume that these params (name and dir) are user input. We should ensure that the canoncicalized path contains the expected directory and file name (see https://cwe.mitre.org/data/definitions/22.html).

**Comment by marbar3778** [comment]
fsdb has been removed
