### ISSUE TITLE
Support connect to remotedb in commandline

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tm-db#73]
We have write `remotedb.go` and `remotedb_test.go` in `tendermint/libs`, but we couldn't put the params into the `toml.go`.

I thought remotedb is very useful when our data is excess the limit of single machine. It could be a cluster made up by leveldb or other database.
And it will decrease the assualt of disk error.

**Comment by blinky3713** [comment]
Somewhat related. I'm the original issue filer for https://github.com/cosmos/iavl/pull/184 and am wondering if I should be following this repo instead. Is the `remotedb` in this repository replacing this PR? Is there documentation about how to use it?

**Comment by marbar3778** [comment]
In an effort to reduce the maintenance cost of this repo, I would propose we remove remotedb.
