### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by mvdan** [tendermint/tm-db#84]
It seems like there is no LICENSE file in this repository. Assuming this was meant to be open source, could you please add one?

**Comment by erikgrinaker** [comment]
Indeed! #85

**Comment by mvdan** [comment]
Thanks for the quick fix! Could someone do a quick scan through all tendermint Go repos, to check if there's another one that was forgotten as well?

**Comment by erikgrinaker** [comment]
I skimmed the Tendermint repos, the only significant one I could find is `js-abci`, which is under MIT but lacks a `LICENSE` file. Opened an issue, since I don't have commit rights: https://github.com/tendermint/js-abci/issues/42
